#!/bin/bash
# creates a new github phprojekt pull request for the current branch

BRANCH=$(git symbolic-ref HEAD 2>/dev/null)
if [ "${BRANCH}" != "" ]; then
    BRANCH="${BRANCH#refs/heads/}"
    echo "create pull request for ${BRANCH}"
    firefox "https://github.com/exi/PHProjekt/pull/new/${BRANCH}"
else
    echo "no branch found"
fi
