#!/bin/bash

case "$1" in
    up)
        qdbus-qt4 org.kde.kmix /kmix/KMixWindow/actions/increase_volume trigger
        ;;
    down)
        qdbus-qt4 org.kde.kmix /kmix/KMixWindow/actions/decrease_volume trigger
        ;;
esac
